/* soapServer.cpp
   Generated by gSOAP 2.8.21 from deviceServices.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.8.21 2015-01-09 20:32:44 GMT")


extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getAvailableSensorsInfo"))
		return soap_serve_ns__getAvailableSensorsInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getCurrentDeviceLocation"))
		return soap_serve_ns__getCurrentDeviceLocation(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:logMessage"))
		return soap_serve_ns__logMessage(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getAvailableSensorsInfo(struct soap *soap)
{	struct ns__getAvailableSensorsInfo soap_tmp_ns__getAvailableSensorsInfo;
	struct ns__SensorArray sensors;
	soap_default_ns__SensorArray(soap, &sensors);
	soap_default_ns__getAvailableSensorsInfo(soap, &soap_tmp_ns__getAvailableSensorsInfo);
	if (!soap_get_ns__getAvailableSensorsInfo(soap, &soap_tmp_ns__getAvailableSensorsInfo, "ns:getAvailableSensorsInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getAvailableSensorsInfo(soap, soap_tmp_ns__getAvailableSensorsInfo._, &sensors);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns__SensorArray(soap, &sensors);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__SensorArray(soap, &sensors, "ns:SensorArray", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__SensorArray(soap, &sensors, "ns:SensorArray", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getCurrentDeviceLocation(struct soap *soap)
{	struct ns__getCurrentDeviceLocation soap_tmp_ns__getCurrentDeviceLocation;
	struct ns__Location location;
	soap_default_ns__Location(soap, &location);
	soap_default_ns__getCurrentDeviceLocation(soap, &soap_tmp_ns__getCurrentDeviceLocation);
	if (!soap_get_ns__getCurrentDeviceLocation(soap, &soap_tmp_ns__getCurrentDeviceLocation, "ns:getCurrentDeviceLocation", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getCurrentDeviceLocation(soap, soap_tmp_ns__getCurrentDeviceLocation._, &location);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns__Location(soap, &location);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__Location(soap, &location, "ns:Location", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__Location(soap, &location, "ns:Location", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__logMessage(struct soap *soap)
{	struct ns__logMessage soap_tmp_ns__logMessage;
	struct ns__Confirmation confirmation;
	soap_default_ns__Confirmation(soap, &confirmation);
	soap_default_ns__logMessage(soap, &soap_tmp_ns__logMessage);
	if (!soap_get_ns__logMessage(soap, &soap_tmp_ns__logMessage, "ns:logMessage", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__logMessage(soap, soap_tmp_ns__logMessage.message, &confirmation);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns__Confirmation(soap, &confirmation);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__Confirmation(soap, &confirmation, "ns:Confirmation", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__Confirmation(soap, &confirmation, "ns:Confirmation", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.cpp */
