/* soapH.h
   Generated by gSOAP 2.8.17r from c:\Users\joHn_ny\Desktop\new\deviceServices.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_byte(soap, data),0) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_int(soap, data),0) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_float
#define SOAP_TYPE_float (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_float(struct soap*, float *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_float(struct soap*, const char*, float *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_float(struct soap*, const float *, const char*, const char*);

#ifndef soap_write_float
#define soap_write_float(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_float(soap, data),0) || soap_put_float(soap, data, "float", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 float * SOAP_FMAC4 soap_get_float(struct soap*, float *, const char*, const char*);

#ifndef soap_read_float
#define soap_read_float(soap, data) ( soap_begin_recv(soap) || !soap_get_float(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap*, double *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap*, const char*, double *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap*, const double *, const char*, const char*);

#ifndef soap_write_double
#define soap_write_double(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_double(soap, data),0) || soap_put_double(soap, data, "double", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap*, double *, const char*, const char*);

#ifndef soap_read_double
#define soap_read_double(soap, data) ( soap_begin_recv(soap) || !soap_get_double(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data),0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(struct soap *soap) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); } return _p; }

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); _p->faultcode = faultcode; _p->faultstring = faultstring; _p->faultactor = faultactor; _p->detail = detail; _p->SOAP_ENV__Code = SOAP_ENV__Code; _p->SOAP_ENV__Reason = SOAP_ENV__Reason; _p->SOAP_ENV__Node = SOAP_ENV__Node; _p->SOAP_ENV__Role = SOAP_ENV__Role; _p->SOAP_ENV__Detail = SOAP_ENV__Detail; } return _p; }

inline void soap_delete_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data),0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(struct soap *soap) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); } return _p; }

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(struct soap *soap, char *SOAP_ENV__Text) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); _p->SOAP_ENV__Text = SOAP_ENV__Text; } return _p; }

inline void soap_delete_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data),0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(struct soap *soap, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__type = __type; _p->fault = fault; } return _p; }

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(struct soap *soap, char *__any, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__any = __any; _p->__type = __type; _p->fault = fault; } return _p; }

inline void soap_delete_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data),0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(struct soap *soap) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); } return _p; }

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); _p->SOAP_ENV__Value = SOAP_ENV__Value; _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode; } return _p; }

inline void soap_delete_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data),0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline void soap_delete_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ns__getCurrentDeviceLocation
#define SOAP_TYPE_ns__getCurrentDeviceLocation (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__getCurrentDeviceLocation(struct soap*, struct ns__getCurrentDeviceLocation *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__getCurrentDeviceLocation(struct soap*, const struct ns__getCurrentDeviceLocation *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__getCurrentDeviceLocation(struct soap*, const char*, int, const struct ns__getCurrentDeviceLocation *, const char*);
SOAP_FMAC3 struct ns__getCurrentDeviceLocation * SOAP_FMAC4 soap_in_ns__getCurrentDeviceLocation(struct soap*, const char*, struct ns__getCurrentDeviceLocation *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__getCurrentDeviceLocation(struct soap*, const struct ns__getCurrentDeviceLocation *, const char*, const char*);

#ifndef soap_write_ns__getCurrentDeviceLocation
#define soap_write_ns__getCurrentDeviceLocation(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__getCurrentDeviceLocation(soap, data),0) || soap_put_ns__getCurrentDeviceLocation(soap, data, "ns:getCurrentDeviceLocation", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__getCurrentDeviceLocation * SOAP_FMAC4 soap_get_ns__getCurrentDeviceLocation(struct soap*, struct ns__getCurrentDeviceLocation *, const char*, const char*);

#ifndef soap_read_ns__getCurrentDeviceLocation
#define soap_read_ns__getCurrentDeviceLocation(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__getCurrentDeviceLocation(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__getCurrentDeviceLocation * SOAP_FMAC2 soap_instantiate_ns__getCurrentDeviceLocation(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__getCurrentDeviceLocation * soap_new_ns__getCurrentDeviceLocation(struct soap *soap, int n = -1) { return soap_instantiate_ns__getCurrentDeviceLocation(soap, n, NULL, NULL, NULL); }

inline struct ns__getCurrentDeviceLocation * soap_new_req_ns__getCurrentDeviceLocation(struct soap *soap) { struct ns__getCurrentDeviceLocation *_p = soap_instantiate_ns__getCurrentDeviceLocation(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__getCurrentDeviceLocation(soap, _p); } return _p; }

inline struct ns__getCurrentDeviceLocation * soap_new_set_ns__getCurrentDeviceLocation(struct soap *soap, void *_) { struct ns__getCurrentDeviceLocation *_p = soap_instantiate_ns__getCurrentDeviceLocation(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__getCurrentDeviceLocation(soap, _p); _p->_ = _; } return _p; }

inline void soap_delete_ns__getCurrentDeviceLocation(struct soap *soap, struct ns__getCurrentDeviceLocation *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__getCurrentDeviceLocation(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__getAvailableSensorsInfo
#define SOAP_TYPE_ns__getAvailableSensorsInfo (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__getAvailableSensorsInfo(struct soap*, struct ns__getAvailableSensorsInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__getAvailableSensorsInfo(struct soap*, const struct ns__getAvailableSensorsInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__getAvailableSensorsInfo(struct soap*, const char*, int, const struct ns__getAvailableSensorsInfo *, const char*);
SOAP_FMAC3 struct ns__getAvailableSensorsInfo * SOAP_FMAC4 soap_in_ns__getAvailableSensorsInfo(struct soap*, const char*, struct ns__getAvailableSensorsInfo *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__getAvailableSensorsInfo(struct soap*, const struct ns__getAvailableSensorsInfo *, const char*, const char*);

#ifndef soap_write_ns__getAvailableSensorsInfo
#define soap_write_ns__getAvailableSensorsInfo(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__getAvailableSensorsInfo(soap, data),0) || soap_put_ns__getAvailableSensorsInfo(soap, data, "ns:getAvailableSensorsInfo", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__getAvailableSensorsInfo * SOAP_FMAC4 soap_get_ns__getAvailableSensorsInfo(struct soap*, struct ns__getAvailableSensorsInfo *, const char*, const char*);

#ifndef soap_read_ns__getAvailableSensorsInfo
#define soap_read_ns__getAvailableSensorsInfo(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__getAvailableSensorsInfo(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__getAvailableSensorsInfo * SOAP_FMAC2 soap_instantiate_ns__getAvailableSensorsInfo(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__getAvailableSensorsInfo * soap_new_ns__getAvailableSensorsInfo(struct soap *soap, int n = -1) { return soap_instantiate_ns__getAvailableSensorsInfo(soap, n, NULL, NULL, NULL); }

inline struct ns__getAvailableSensorsInfo * soap_new_req_ns__getAvailableSensorsInfo(struct soap *soap) { struct ns__getAvailableSensorsInfo *_p = soap_instantiate_ns__getAvailableSensorsInfo(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__getAvailableSensorsInfo(soap, _p); } return _p; }

inline struct ns__getAvailableSensorsInfo * soap_new_set_ns__getAvailableSensorsInfo(struct soap *soap, void *_) { struct ns__getAvailableSensorsInfo *_p = soap_instantiate_ns__getAvailableSensorsInfo(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__getAvailableSensorsInfo(soap, _p); _p->_ = _; } return _p; }

inline void soap_delete_ns__getAvailableSensorsInfo(struct soap *soap, struct ns__getAvailableSensorsInfo *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__getAvailableSensorsInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__Location
#define SOAP_TYPE_ns__Location (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__Location(struct soap*, struct ns__Location *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__Location(struct soap*, const struct ns__Location *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__Location(struct soap*, const char*, int, const struct ns__Location *, const char*);
SOAP_FMAC3 struct ns__Location * SOAP_FMAC4 soap_in_ns__Location(struct soap*, const char*, struct ns__Location *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__Location(struct soap*, const struct ns__Location *, const char*, const char*);

#ifndef soap_write_ns__Location
#define soap_write_ns__Location(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__Location(soap, data),0) || soap_put_ns__Location(soap, data, "ns:Location", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__Location * SOAP_FMAC4 soap_get_ns__Location(struct soap*, struct ns__Location *, const char*, const char*);

#ifndef soap_read_ns__Location
#define soap_read_ns__Location(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__Location(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__Location * SOAP_FMAC2 soap_instantiate_ns__Location(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__Location * soap_new_ns__Location(struct soap *soap, int n = -1) { return soap_instantiate_ns__Location(soap, n, NULL, NULL, NULL); }

inline struct ns__Location * soap_new_req_ns__Location(struct soap *soap, double longitude, double latitude) { struct ns__Location *_p = soap_instantiate_ns__Location(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__Location(soap, _p); _p->longitude = longitude; _p->latitude = latitude; } return _p; }

inline struct ns__Location * soap_new_set_ns__Location(struct soap *soap, double longitude, double latitude) { struct ns__Location *_p = soap_instantiate_ns__Location(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__Location(soap, _p); _p->longitude = longitude; _p->latitude = latitude; } return _p; }

inline void soap_delete_ns__Location(struct soap *soap, struct ns__Location *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__Location(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__SensorArray
#define SOAP_TYPE_ns__SensorArray (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__SensorArray(struct soap*, struct ns__SensorArray *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__SensorArray(struct soap*, const struct ns__SensorArray *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__SensorArray(struct soap*, const char*, int, const struct ns__SensorArray *, const char*);
SOAP_FMAC3 struct ns__SensorArray * SOAP_FMAC4 soap_in_ns__SensorArray(struct soap*, const char*, struct ns__SensorArray *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__SensorArray(struct soap*, const struct ns__SensorArray *, const char*, const char*);

#ifndef soap_write_ns__SensorArray
#define soap_write_ns__SensorArray(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__SensorArray(soap, data),0) || soap_put_ns__SensorArray(soap, data, "ns:SensorArray", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__SensorArray * SOAP_FMAC4 soap_get_ns__SensorArray(struct soap*, struct ns__SensorArray *, const char*, const char*);

#ifndef soap_read_ns__SensorArray
#define soap_read_ns__SensorArray(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__SensorArray(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__SensorArray * SOAP_FMAC2 soap_instantiate_ns__SensorArray(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__SensorArray * soap_new_ns__SensorArray(struct soap *soap, int n = -1) { return soap_instantiate_ns__SensorArray(soap, n, NULL, NULL, NULL); }

inline struct ns__SensorArray * soap_new_req_ns__SensorArray(struct soap *soap, int __size, struct ns__Sensor *sensors) { struct ns__SensorArray *_p = soap_instantiate_ns__SensorArray(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__SensorArray(soap, _p); _p->__size = __size; _p->sensors = sensors; } return _p; }

inline struct ns__SensorArray * soap_new_set_ns__SensorArray(struct soap *soap, int __size, struct ns__Sensor *sensors) { struct ns__SensorArray *_p = soap_instantiate_ns__SensorArray(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__SensorArray(soap, _p); _p->__size = __size; _p->sensors = sensors; } return _p; }

inline void soap_delete_ns__SensorArray(struct soap *soap, struct ns__SensorArray *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__SensorArray(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__Sensor
#define SOAP_TYPE_ns__Sensor (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__Sensor(struct soap*, struct ns__Sensor *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__Sensor(struct soap*, const struct ns__Sensor *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__Sensor(struct soap*, const char*, int, const struct ns__Sensor *, const char*);
SOAP_FMAC3 struct ns__Sensor * SOAP_FMAC4 soap_in_ns__Sensor(struct soap*, const char*, struct ns__Sensor *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__Sensor(struct soap*, const struct ns__Sensor *, const char*, const char*);

#ifndef soap_write_ns__Sensor
#define soap_write_ns__Sensor(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__Sensor(soap, data),0) || soap_put_ns__Sensor(soap, data, "ns:Sensor", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__Sensor * SOAP_FMAC4 soap_get_ns__Sensor(struct soap*, struct ns__Sensor *, const char*, const char*);

#ifndef soap_read_ns__Sensor
#define soap_read_ns__Sensor(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__Sensor(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__Sensor * SOAP_FMAC2 soap_instantiate_ns__Sensor(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__Sensor * soap_new_ns__Sensor(struct soap *soap, int n = -1) { return soap_instantiate_ns__Sensor(soap, n, NULL, NULL, NULL); }

inline struct ns__Sensor * soap_new_req_ns__Sensor(struct soap *soap, int mVersion, int mType, float mMaxRange, float mResolution, float mPower, int mMinDelay) { struct ns__Sensor *_p = soap_instantiate_ns__Sensor(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__Sensor(soap, _p); _p->mVersion = mVersion; _p->mType = mType; _p->mMaxRange = mMaxRange; _p->mResolution = mResolution; _p->mPower = mPower; _p->mMinDelay = mMinDelay; } return _p; }

inline struct ns__Sensor * soap_new_set_ns__Sensor(struct soap *soap, char *mName, char *mVendor, int mVersion, int mType, float mMaxRange, float mResolution, float mPower, int mMinDelay) { struct ns__Sensor *_p = soap_instantiate_ns__Sensor(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__Sensor(soap, _p); _p->mName = mName; _p->mVendor = mVendor; _p->mVersion = mVersion; _p->mType = mType; _p->mMaxRange = mMaxRange; _p->mResolution = mResolution; _p->mPower = mPower; _p->mMinDelay = mMinDelay; } return _p; }

inline void soap_delete_ns__Sensor(struct soap *soap, struct ns__Sensor *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__Sensor(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data),0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data),0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data),0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTons__Location
#define SOAP_TYPE_PointerTons__Location (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__Location(struct soap*, struct ns__Location *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__Location(struct soap*, const char *, int, struct ns__Location *const*, const char *);
SOAP_FMAC3 struct ns__Location ** SOAP_FMAC4 soap_in_PointerTons__Location(struct soap*, const char*, struct ns__Location **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__Location(struct soap*, struct ns__Location *const*, const char*, const char*);

#ifndef soap_write_PointerTons__Location
#define soap_write_PointerTons__Location(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons__Location(soap, data),0) || soap_put_PointerTons__Location(soap, data, "ns:Location", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__Location ** SOAP_FMAC4 soap_get_PointerTons__Location(struct soap*, struct ns__Location **, const char*, const char*);

#ifndef soap_read_PointerTons__Location
#define soap_read_PointerTons__Location(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons__Location(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons__SensorArray
#define SOAP_TYPE_PointerTons__SensorArray (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__SensorArray(struct soap*, struct ns__SensorArray *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__SensorArray(struct soap*, const char *, int, struct ns__SensorArray *const*, const char *);
SOAP_FMAC3 struct ns__SensorArray ** SOAP_FMAC4 soap_in_PointerTons__SensorArray(struct soap*, const char*, struct ns__SensorArray **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__SensorArray(struct soap*, struct ns__SensorArray *const*, const char*, const char*);

#ifndef soap_write_PointerTons__SensorArray
#define soap_write_PointerTons__SensorArray(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons__SensorArray(soap, data),0) || soap_put_PointerTons__SensorArray(soap, data, "ns:SensorArray", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__SensorArray ** SOAP_FMAC4 soap_get_PointerTons__SensorArray(struct soap*, struct ns__SensorArray **, const char*, const char*);

#ifndef soap_read_PointerTons__SensorArray
#define soap_read_PointerTons__SensorArray(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons__SensorArray(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons__Sensor
#define SOAP_TYPE_PointerTons__Sensor (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__Sensor(struct soap*, struct ns__Sensor *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__Sensor(struct soap*, const char *, int, struct ns__Sensor *const*, const char *);
SOAP_FMAC3 struct ns__Sensor ** SOAP_FMAC4 soap_in_PointerTons__Sensor(struct soap*, const char*, struct ns__Sensor **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__Sensor(struct soap*, struct ns__Sensor *const*, const char*, const char*);

#ifndef soap_write_PointerTons__Sensor
#define soap_write_PointerTons__Sensor(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons__Sensor(soap, data),0) || soap_put_PointerTons__Sensor(soap, data, "ns:Sensor", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__Sensor ** SOAP_FMAC4 soap_get_PointerTons__Sensor(struct soap*, struct ns__Sensor **, const char*, const char*);

#ifndef soap_read_PointerTons__Sensor
#define soap_read_PointerTons__Sensor(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons__Sensor(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__QName(soap, data),0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_string(soap, data),0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

/* End of soapH.h */
